disabled_rules: # rule identifiers to exclude from running
  - inclusive_language
included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - Example/Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Example/Resources

# configurable rules can be customized from this configuration file.
# colon behavior when specifying types or defining dictionaries
colon:
  apply_to_dictionaries: false
# complexity of a function
cyclomatic_complexity:
  error: 5
  warning: 5
# number of lines allowed in a function
function_body_length:
  error: 45
  warning: 40
# number of parameters allowed for a function
function_parameter_count: 5
# number of lines allowed in a file
file_length:
  error: 265
  warning: 260
# rules related to vars/lets
identifier_name:
  excluded:
    - id
# number of characters allowed in a line
line_length:
  error: 190
  ignores_comments: true
  ignores_function_declarations: true
  warning: 185
# number of lines allowed in a type declaration
type_body_length:
  error: 170
  warning: 165
